version: "3.9"

services:
  order_db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB}
    volumes:
      - ./database/01_orders.sql:/docker-entrypoint-initdb.d/01_orders.sql
    ports:
      - "5433:5432"

  inventory_db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_USER: ${INVENTORY_DB_USER}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD}
      POSTGRES_DB: ${INVENTORY_DB}
    volumes:
      - ./database/02_inventory.sql:/docker-entrypoint-initdb.d/02_inventory.sql
    ports:
      - "5434:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  order_service:
    build: ./server/order_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - order_db
    environment:
      - ORDER_DB_HOST=order_db  
      - DB_NAME=${ORDER_DB}

  inventory_service:
    build: ./server/inventory_service
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - inventory_db
    environment:
      - INVENTORY_DB_HOST=inventory_db
      - DB_NAME=${INVENTORY_DB}